import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#0e0e0e',
        'text-secondary': '#A1A1AA',
        tertiary: '#ffb873',
        'secondary-container': '#00a572',
        'surface-container-high': '#2a2a2a',
        'on-tertiary-fixed-variant': '#6a3b00',
        secondary: '#4edea3',
        background: '#131313',
        'surface-variant': '#353534',
        'on-primary-fixed': '#001f26',
        'on-primary-fixed-variant': '#004e5c',
        'on-surface-variant': '#bcc9cd',
        'outline-variant': '#3d494c',
        'on-secondary-fixed': '#002113',
        'inverse-surface': '#e5e2e1',
        'on-error-container': '#ffdad6',
        'secondary-fixed-dim': '#4edea3',
        'primary-fixed': '#acedff',
        'on-tertiary-fixed': '#2d1600',
        'text-primary': '#FFFFFF',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-tertiary': '#4b2800',
        'surface-bright': '#3a3939',
        'surface-container': '#201f1f',
        'tertiary-container': '#e89337',
        'text-tertiary': '#71717A',
        'inverse-on-surface': '#313030',
        'surface-container-low': '#1c1b1b',
        'inverse-primary': '#00687a',
        'border-strong': '#27272A',
        'on-surface': '#e5e2e1',
        'on-secondary-fixed-variant': '#005236',
        'surface-base': '#050505',
        'tertiary-fixed-dim': '#ffb873',
        'on-secondary-container': '#00311f',
        'on-background': '#e5e2e1',
        'on-tertiary-container': '#5b3200',
        'primary-fixed-dim': '#4cd7f6',
        surface: '#131313',
        outline: '#869397',
        'secondary-fixed': '#6ffbbe',
        'primary-container': '#06b6d4',
        'on-primary': '#003640',
        'surface-tint': '#4cd7f6',
        'tertiary-fixed': '#ffdcbf',
        'border-subtle': 'rgba(255, 255, 255, 0.08)',
        error: '#ffb4ab',
        'surface-dim': '#131313',
        'on-primary-container': '#00424f',
        primary: '#4cd7f6',
        'surface-container-highest': '#353534',
        'surface-elevated': '#0D0D0F',
        'surface-overlay': '#18181B',
        'on-secondary': '#003824',
      },
      fontFamily: {
        sans: ['Geist', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        geist: ['Geist', 'sans-serif'],
      },
      spacing: {
        'margin-desktop': '3rem',
        'space-sm': '0.5rem',
        'space-xs': '0.25rem',
        'space-lg': '1.5rem',
        'gutter-tablet': '1.5rem',
        'margin-tablet': '2rem',
        'space-xl': '2.5rem',
        'gutter-desktop': '2rem',
        'space-md': '1rem',
        'space-2xl': '4rem',
        gutter: '1rem',
      },
    },
  },
  plugins: [],
} satisfies Config;
